# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-json
      - id: check-toml
      - id: check-merge-conflict
      - id: check-docstring-first
      - id: debug-statements
      - id: mixed-line-ending
      # Security checks
      - id: check-ast
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: detect-private-key

  # Detect secrets in commits
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package-lock\.json

  # Check for security issues
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
        args: ['-ll', '-i', '-x', 'tests,venv,env,3d_detection_env']

  # Additional file checks
  - repo: local
    hooks:
      - id: check-sensitive-files
        name: Check for sensitive files
        entry: >
          bash -c 'git diff --cached --name-only --diff-filter=ACM |
          grep -E "\.(pem|key|p12|pfx|jks|cert|crt|cer|env|secret)$" &&
          echo "ERROR: Attempting to commit sensitive files!" && exit 1 || exit 0'
        language: system
        pass_filenames: false
      - id: check-env-files
        name: Block .env files
        entry: >
          bash -c 'git diff --cached --name-only |
          grep -E "(^|/)\.env($|\.)" |
          grep -v "\.env\.example" &&
          echo "ERROR: .env files must not be committed!" && exit 1 || exit 0'
        language: system
        pass_filenames: false

  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.9
    hooks:
      # Run the linter.
      - id: ruff
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
